# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.3.0b1
_src_path: https://github.com/climate-resource/copier-bookshelf-dataset.git
author: Jared Lewis
author_email: jared.lewis@climate-resource.com
dataset_description: National historical greenhouse gas emissions for every country
    and Kyoto gas from 1750.
dataset_name: primap-hist
dataset_name_human: PRIMAP-hist
project_url: https://github.com/climate-resource/bookshelf-primap-hist
